2022-06-08 17:05:04,418 INFO: logging in using static token
2022-06-08 17:05:04,733 INFO: Shard ID None has sent the IDENTIFY payload.
2022-06-08 17:05:04,884 INFO: Shard ID None has connected to Gateway: ["gateway-prd-main-wft8",{"micros":110784,"calls":["discord-sessions-blue-prd-2-25",{"micros":109119,"calls":["start_session",{"micros":92575,"calls":["discord-api-59f5fc6648-r46sb",{"micros":87200,"calls":["get_user",{"micros":32515},"add_authorized_ip",{"micros":13637},"get_guilds",{"micros":5316},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":3622,"calls":[]}]}]}] (Session ID: 7ec47149c37d35aaf7970253d661894a).
2022-06-08 17:05:06,935 INFO: 目前登入身份：神奇海螺#3847
2022-06-08 18:28:56,787 INFO: Websocket closed with 1006, attempting a reconnect.
2022-06-08 18:28:56,787 INFO: Got a request to RESUME the websocket.
2022-06-08 18:28:56,983 INFO: Shard ID None has sent the RESUME payload.
2022-06-08 18:28:57,026 INFO: Shard ID None has successfully RESUMED session 7ec47149c37d35aaf7970253d661894a under trace ["gateway-prd-main-z790",{"micros":552,"calls":["discord-sessions-blue-prd-2-25",{"micros":26}]}].
2022-06-08 18:47:25,375 INFO: Websocket closed with 1006, attempting a reconnect.
2022-06-08 18:47:25,376 INFO: Got a request to RESUME the websocket.
2022-06-08 18:47:25,581 INFO: Shard ID None has sent the RESUME payload.
2022-06-08 18:47:25,633 INFO: Shard ID None has successfully RESUMED session 7ec47149c37d35aaf7970253d661894a under trace ["gateway-prd-main-7jx0",{"micros":5217,"calls":["discord-sessions-blue-prd-2-25",{"micros":20}]}].
2022-06-08 20:57:52,377 INFO: Websocket closed with 1006, attempting a reconnect.
2022-06-08 20:57:52,377 INFO: Got a request to RESUME the websocket.
2022-06-08 20:57:52,549 INFO: Shard ID None has sent the RESUME payload.
2022-06-08 20:57:52,592 INFO: Shard ID None has successfully RESUMED session 7ec47149c37d35aaf7970253d661894a under trace ["gateway-prd-main-vdr1",{"micros":3790,"calls":["discord-sessions-blue-prd-2-25",{"micros":21}]}].
2022-06-08 23:02:02,009 INFO: logging in using static token
2022-06-08 23:02:02,081 INFO: Cleaning up tasks.
2022-06-08 23:02:02,082 INFO: Closing the event loop.
2022-06-08 23:06:23,241 INFO: logging in using static token
2022-06-08 23:06:23,306 INFO: Cleaning up tasks.
2022-06-08 23:06:23,306 INFO: Closing the event loop.
2022-06-08 23:21:24,019 INFO: logging in using static token
2022-06-08 23:21:24,087 INFO: Cleaning up tasks.
2022-06-08 23:21:24,088 INFO: Closing the event loop.
2022-06-08 23:36:24,015 INFO: logging in using static token
2022-06-08 23:36:24,091 INFO: Cleaning up tasks.
2022-06-08 23:36:24,092 INFO: Closing the event loop.
2022-06-08 23:51:24,144 INFO: logging in using static token
2022-06-08 23:51:24,228 INFO: Cleaning up tasks.
2022-06-08 23:51:24,228 INFO: Closing the event loop.
2022-06-09 00:01:53,371 INFO: logging in using static token
2022-06-09 00:01:53,457 INFO: Cleaning up tasks.
2022-06-09 00:01:53,457 INFO: Closing the event loop.
2022-06-09 00:02:27,507 INFO: logging in using static token
2022-06-09 00:02:27,577 INFO: Cleaning up tasks.
2022-06-09 00:02:27,577 INFO: Closing the event loop.
2022-06-09 00:06:24,220 INFO: logging in using static token
2022-06-09 00:06:24,284 INFO: Cleaning up tasks.
2022-06-09 00:06:24,285 INFO: Closing the event loop.
2022-06-09 00:21:24,238 INFO: logging in using static token
2022-06-09 00:21:24,302 INFO: Cleaning up tasks.
2022-06-09 00:21:24,303 INFO: Closing the event loop.
2022-06-09 00:36:24,623 INFO: logging in using static token
2022-06-09 00:36:24,696 INFO: Cleaning up tasks.
2022-06-09 00:36:24,696 INFO: Closing the event loop.
2022-06-09 00:51:24,541 INFO: logging in using static token
2022-06-09 00:51:24,608 INFO: Cleaning up tasks.
2022-06-09 00:51:24,609 INFO: Closing the event loop.
2022-06-09 01:02:30,003 INFO: logging in using static token
2022-06-09 01:02:30,087 INFO: Cleaning up tasks.
2022-06-09 01:02:30,088 INFO: Closing the event loop.
2022-06-09 01:06:25,356 INFO: logging in using static token
2022-06-09 01:06:25,437 INFO: Cleaning up tasks.
2022-06-09 01:06:25,437 INFO: Closing the event loop.
2022-06-09 01:21:24,392 INFO: logging in using static token
2022-06-09 01:21:24,460 INFO: Cleaning up tasks.
2022-06-09 01:21:24,461 INFO: Closing the event loop.
2022-06-09 01:36:24,259 INFO: logging in using static token
2022-06-09 01:36:24,436 INFO: Cleaning up tasks.
2022-06-09 01:36:24,436 INFO: Closing the event loop.
2022-06-09 01:51:24,935 INFO: logging in using static token
2022-06-09 01:51:25,025 INFO: Cleaning up tasks.
2022-06-09 01:51:25,025 INFO: Closing the event loop.
2022-06-09 02:02:33,272 INFO: logging in using static token
2022-06-09 02:02:33,348 INFO: Cleaning up tasks.
2022-06-09 02:02:33,348 INFO: Closing the event loop.
2022-06-09 02:06:24,862 INFO: logging in using static token
2022-06-09 02:06:24,957 INFO: Cleaning up tasks.
2022-06-09 02:06:24,957 INFO: Closing the event loop.
2022-06-09 02:21:25,458 INFO: logging in using static token
2022-06-09 02:21:25,538 INFO: Cleaning up tasks.
2022-06-09 02:21:25,538 INFO: Closing the event loop.
2022-06-09 02:36:25,475 INFO: logging in using static token
2022-06-09 02:36:25,549 INFO: Cleaning up tasks.
2022-06-09 02:36:25,550 INFO: Closing the event loop.
2022-06-09 02:51:26,017 INFO: logging in using static token
2022-06-09 02:51:26,085 INFO: Cleaning up tasks.
2022-06-09 02:51:26,085 INFO: Closing the event loop.
2022-06-09 03:02:37,076 INFO: logging in using static token
2022-06-09 03:02:37,147 INFO: Cleaning up tasks.
2022-06-09 03:02:37,147 INFO: Closing the event loop.
2022-06-09 03:06:26,082 INFO: logging in using static token
2022-06-09 03:06:26,167 INFO: Cleaning up tasks.
2022-06-09 03:06:26,168 INFO: Closing the event loop.
2022-06-09 03:21:32,208 INFO: logging in using static token
2022-06-09 03:21:32,338 INFO: Cleaning up tasks.
2022-06-09 03:21:32,338 INFO: Closing the event loop.
2022-06-09 03:36:33,717 INFO: logging in using static token
2022-06-09 03:36:33,794 INFO: Cleaning up tasks.
2022-06-09 03:36:33,795 INFO: Closing the event loop.
2022-06-09 03:51:41,580 INFO: logging in using static token
2022-06-09 03:51:41,854 INFO: Shard ID None has sent the IDENTIFY payload.
2022-06-09 03:51:42,064 INFO: Shard ID None has connected to Gateway: ["gateway-prd-main-s894",{"micros":148596,"calls":["discord-sessions-blue-prd-2-31",{"micros":147826,"calls":["start_session",{"micros":42905,"calls":["discord-api-5cbd4675f4-gxlt9",{"micros":34807,"calls":["get_user",{"micros":6906},"add_authorized_ip",{"micros":1680},"get_guilds",{"micros":4312},"coros_wait",{"micros":2}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 96b7f3ebce133411cc0e9ffcaae28f78).
2022-06-09 03:51:44,320 INFO: 目前登入身份：神奇海螺#3847
2022-06-09 04:34:42,320 INFO: logging in using static token
2022-06-09 04:34:42,591 INFO: Shard ID None has sent the IDENTIFY payload.
2022-06-09 04:34:42,713 INFO: Shard ID None has connected to Gateway: ["gateway-prd-main-wft8",{"micros":80674,"calls":["discord-sessions-blue-prd-2-76",{"micros":79933,"calls":["start_session",{"micros":46480,"calls":["discord-api-5cbd4675f4-lxmsc",{"micros":38578,"calls":["get_user",{"micros":9238},"add_authorized_ip",{"micros":1500},"get_guilds",{"micros":6091},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":22287,"calls":[]}]}]}] (Session ID: 1a0d4ca0f61e8c0920fa022a2ba24fef).
2022-06-09 04:34:44,804 INFO: 目前登入身份：神奇海螺#3847
2022-06-09 04:45:12,865 INFO: logging in using static token
2022-06-09 04:45:13,108 INFO: Shard ID None has sent the IDENTIFY payload.
2022-06-09 04:45:13,305 INFO: Shard ID None has connected to Gateway: ["gateway-prd-main-q78x",{"micros":160126,"calls":["discord-sessions-blue-prd-2-141",{"micros":159339,"calls":["start_session",{"micros":110173,"calls":["discord-api-5cbd4675f4-fqqpx",{"micros":89559,"calls":["get_user",{"micros":16375},"add_authorized_ip",{"micros":1696},"get_guilds",{"micros":10212},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":23,"calls":[]},"presence_connect",{"micros":26208,"calls":[]}]}]}] (Session ID: cb23a72611c8430947ad0dc4135bcdb6).
2022-06-09 04:45:15,350 INFO: 目前登入身份：神奇海螺#3847
2022-06-09 06:44:50,776 INFO: Websocket closed with 1006, attempting a reconnect.
2022-06-09 06:44:50,776 INFO: Got a request to RESUME the websocket.
2022-06-09 06:44:50,933 INFO: Shard ID None has sent the RESUME payload.
2022-06-09 06:44:50,971 INFO: Shard ID None has successfully RESUMED session cb23a72611c8430947ad0dc4135bcdb6 under trace ["gateway-prd-main-mtnc",{"micros":426,"calls":["discord-sessions-blue-prd-2-141",{"micros":15}]}].
2022-06-09 07:57:06,606 INFO: Got a request to RESUME the websocket.
2022-06-09 07:57:06,766 INFO: Shard ID None has sent the RESUME payload.
2022-06-09 07:57:06,803 INFO: Shard ID None has successfully RESUMED session cb23a72611c8430947ad0dc4135bcdb6 under trace ["gateway-prd-main-d8qq",{"micros":623,"calls":["discord-sessions-blue-prd-2-141",{"micros":16}]}].
2022-06-09 09:35:19,566 INFO: Got a request to RESUME the websocket.
2022-06-09 09:35:19,727 INFO: Shard ID None has sent the RESUME payload.
2022-06-09 09:35:19,764 INFO: Shard ID None has successfully RESUMED session cb23a72611c8430947ad0dc4135bcdb6 under trace ["gateway-prd-main-rcjz",{"micros":662,"calls":["discord-sessions-blue-prd-2-141",{"micros":16}]}].
2022-06-09 09:41:03,271 INFO: Websocket closed with 1006, attempting a reconnect.
2022-06-09 09:41:03,272 INFO: Got a request to RESUME the websocket.
2022-06-09 09:41:03,433 INFO: Shard ID None has sent the RESUME payload.
2022-06-09 09:41:03,473 INFO: Shard ID None has successfully RESUMED session cb23a72611c8430947ad0dc4135bcdb6 under trace ["gateway-prd-main-76tx",{"micros":718,"calls":["discord-sessions-blue-prd-2-141",{"micros":21}]}].
2022-06-09 12:47:20,712 INFO: Got a request to RESUME the websocket.
2022-06-09 12:47:20,904 INFO: Shard ID None has sent the RESUME payload.
2022-06-09 12:47:20,944 INFO: Shard ID None has successfully RESUMED session cb23a72611c8430947ad0dc4135bcdb6 under trace ["gateway-prd-main-bkx1",{"micros":567,"calls":["discord-sessions-blue-prd-2-141",{"micros":20}]}].
2022-06-09 13:09:50,695 INFO: 神奇海螺 in 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 13:09:50,730 INFO: Connecting to voice...
2022-06-09 13:09:50,730 INFO: Starting voice handshake... (connection attempt 1)
2022-06-09 13:09:51,244 INFO: Voice handshake complete. Endpoint found japan8919.discord.media
2022-06-09 13:09:51,394 ERROR: Exception occurred during Voice Protocol voice server update handler
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/state.py", line 102, in logging_coroutine
    await coroutine
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/voice_client.py", line 295, in on_voice_server_update
    await self.ws.close(4000)
AttributeError: 'NoneType' object has no attribute 'close'
2022-06-09 13:09:52,259 INFO: selected the voice protocol for use (xsalsa20_poly1305_lite)
2022-06-09 13:09:52,439 INFO: received secret key for voice connection
2022-06-09 13:09:54,843 INFO: Preparing to terminate ffmpeg process 1460.
2022-06-09 13:09:54,844 INFO: ffmpeg process 1460 successfully terminated with return code of 0.
2022-06-09 13:09:56,911 INFO: Preparing to terminate ffmpeg process 1471.
2022-06-09 13:09:56,912 INFO: ffmpeg process 1471 successfully terminated with return code of 0.
2022-06-09 13:09:57,938 INFO: The voice handshake is being terminated for Channel ID 728631391809437746 (Guild ID 428109526550708234)
2022-06-09 13:09:57,939 INFO: Disconnecting from voice normally, close code 1000.
2022-06-09 13:19:27,219 INFO: SparkleZ in 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 13:19:27,290 INFO: Connecting to voice...
2022-06-09 13:19:27,291 INFO: Starting voice handshake... (connection attempt 1)
2022-06-09 13:19:27,964 INFO: Voice handshake complete. Endpoint found japan8919.discord.media
2022-06-09 13:19:28,966 INFO: selected the voice protocol for use (xsalsa20_poly1305_lite)
2022-06-09 13:19:29,132 INFO: received secret key for voice connection
2022-06-09 13:19:31,642 INFO: Preparing to terminate ffmpeg process 1482.
2022-06-09 13:19:31,643 INFO: ffmpeg process 1482 successfully terminated with return code of 0.
2022-06-09 13:19:34,493 INFO: Preparing to terminate ffmpeg process 1492.
2022-06-09 13:19:34,494 INFO: ffmpeg process 1492 successfully terminated with return code of 0.
2022-06-09 13:19:35,583 INFO: The voice handshake is being terminated for Channel ID 728631391809437746 (Guild ID 428109526550708234)
2022-06-09 13:19:35,584 INFO: Disconnecting from voice normally, close code 1000.
2022-06-09 14:15:42,938 INFO: BunnyplayGG in 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 14:15:42,986 INFO: Connecting to voice...
2022-06-09 14:15:42,987 INFO: Starting voice handshake... (connection attempt 1)
2022-06-09 14:15:43,623 INFO: Voice handshake complete. Endpoint found japan8919.discord.media
2022-06-09 14:15:44,623 INFO: selected the voice protocol for use (xsalsa20_poly1305_lite)
2022-06-09 14:15:44,792 INFO: received secret key for voice connection
2022-06-09 14:15:46,661 INFO: Preparing to terminate ffmpeg process 1656.
2022-06-09 14:15:46,661 INFO: ffmpeg process 1656 successfully terminated with return code of 0.
2022-06-09 14:15:49,378 INFO: Preparing to terminate ffmpeg process 1666.
2022-06-09 14:15:49,379 INFO: ffmpeg process 1666 successfully terminated with return code of 0.
2022-06-09 14:15:50,423 INFO: The voice handshake is being terminated for Channel ID 728631391809437746 (Guild ID 428109526550708234)
2022-06-09 14:15:50,424 INFO: Disconnecting from voice normally, close code 1000.
2022-06-09 14:18:55,381 INFO: SparkleZ out 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 14:18:55,381 INFO: Connecting to voice...
2022-06-09 14:18:55,381 INFO: Starting voice handshake... (connection attempt 1)
2022-06-09 14:18:56,129 INFO: Voice handshake complete. Endpoint found japan8919.discord.media
2022-06-09 14:18:56,364 INFO: SparkleZ in 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 14:18:57,133 INFO: selected the voice protocol for use (xsalsa20_poly1305_lite)
2022-06-09 14:18:57,301 INFO: received secret key for voice connection
2022-06-09 14:18:59,301 INFO: Preparing to terminate ffmpeg process 1677.
2022-06-09 14:18:59,302 INFO: ffmpeg process 1677 successfully terminated with return code of 0.
2022-06-09 14:19:02,332 INFO: Preparing to terminate ffmpeg process 1687.
2022-06-09 14:19:02,333 INFO: ffmpeg process 1687 successfully terminated with return code of 0.
2022-06-09 14:19:05,002 INFO: Preparing to terminate ffmpeg process 1697.
2022-06-09 14:19:05,003 INFO: ffmpeg process 1697 successfully terminated with return code of 0.
2022-06-09 14:19:06,012 INFO: The voice handshake is being terminated for Channel ID 728631391809437746 (Guild ID 428109526550708234)
2022-06-09 14:19:06,012 INFO: Disconnecting from voice normally, close code 1000.
2022-06-09 14:27:02,011 INFO: SparkleZ out 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 14:27:02,011 INFO: Connecting to voice...
2022-06-09 14:27:02,012 INFO: Starting voice handshake... (connection attempt 1)
2022-06-09 14:27:02,723 INFO: Voice handshake complete. Endpoint found japan8919.discord.media
2022-06-09 14:27:03,718 INFO: selected the voice protocol for use (xsalsa20_poly1305_lite)
2022-06-09 14:27:03,882 INFO: received secret key for voice connection
2022-06-09 14:27:05,875 INFO: Preparing to terminate ffmpeg process 1739.
2022-06-09 14:27:05,875 INFO: ffmpeg process 1739 successfully terminated with return code of 0.
2022-06-09 14:27:06,906 INFO: The voice handshake is being terminated for Channel ID 728631391809437746 (Guild ID 428109526550708234)
2022-06-09 14:27:06,907 INFO: Disconnecting from voice normally, close code 1000.
2022-06-09 14:27:08,626 INFO: Chi in 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 14:27:08,695 INFO: Connecting to voice...
2022-06-09 14:27:08,696 INFO: Starting voice handshake... (connection attempt 1)
2022-06-09 14:27:08,915 INFO: Voice handshake complete. Endpoint found japan8919.discord.media
2022-06-09 14:27:09,891 INFO: selected the voice protocol for use (xsalsa20_poly1305_lite)
2022-06-09 14:27:10,057 INFO: received secret key for voice connection
2022-06-09 14:27:11,726 INFO: Preparing to terminate ffmpeg process 1750.
2022-06-09 14:27:11,726 INFO: ffmpeg process 1750 successfully terminated with return code of 0.
2022-06-09 14:27:13,925 INFO: Preparing to terminate ffmpeg process 1760.
2022-06-09 14:27:13,926 INFO: ffmpeg process 1760 successfully terminated with return code of 0.
2022-06-09 14:27:14,996 INFO: The voice handshake is being terminated for Channel ID 728631391809437746 (Guild ID 428109526550708234)
2022-06-09 14:27:14,997 INFO: Disconnecting from voice normally, close code 1000.
2022-06-09 15:28:23,790 WARNING: Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:28:33,791 WARNING: Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:28:43,793 WARNING: Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:28:53,794 WARNING: Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:29:03,795 WARNING: Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:29:13,799 WARNING: Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:29:23,801 WARNING: Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:29:33,803 WARNING: Shard ID None heartbeat blocked for more than 80 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:29:43,809 WARNING: Shard ID None heartbeat blocked for more than 90 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:29:53,810 WARNING: Shard ID None heartbeat blocked for more than 100 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:30:03,810 WARNING: Shard ID None heartbeat blocked for more than 110 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:30:13,811 WARNING: Shard ID None heartbeat blocked for more than 120 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:30:23,819 WARNING: Shard ID None heartbeat blocked for more than 130 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:30:33,820 WARNING: Shard ID None heartbeat blocked for more than 140 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:30:43,821 WARNING: Shard ID None heartbeat blocked for more than 150 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:30:53,822 WARNING: Shard ID None heartbeat blocked for more than 160 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 430, in <module>
    client.run(os.environ['BOT_TOKEN'])
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 28, in on_voice_state_update
    if (db["mode"] == "0"):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 439, in __getitem__
    raw_val = self.get_raw(key)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 477, in get_raw
    r = self.sess.get(self.db_url + "/" + urllib.parse.quote(key))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

2022-06-09 15:31:03,492 INFO: Timed out receiving packet. Attempting a reconnect.
2022-06-09 15:31:03,492 INFO: Got a request to RESUME the websocket.
2022-06-09 15:31:03,673 INFO: Shard ID None has sent the RESUME payload.
2022-06-09 15:31:03,716 INFO: Shard ID None session has been invalidated.
2022-06-09 15:31:03,756 INFO: Got a request to IDENTIFY the websocket.
2022-06-09 15:31:08,878 INFO: Shard ID None has sent the IDENTIFY payload.
2022-06-09 15:31:09,002 INFO: Shard ID None has connected to Gateway: ["gateway-prd-main-7dz7",{"micros":63976,"calls":["discord-sessions-blue-prd-2-114",{"micros":62903,"calls":["start_session",{"micros":60943,"calls":["discord-api-7bb9cf8b55-6p97d",{"micros":54269,"calls":["get_user",{"micros":27178},"add_authorized_ip",{"micros":1752},"get_guilds",{"micros":4944},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":3,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 019ed78adcc5c1e7f8b6bb52e086e5a1).
2022-06-09 15:31:11,160 INFO: 目前登入身份：神奇海螺#3847
2022-06-09 15:33:22,525 INFO: KyrieR out 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 15:33:22,525 INFO: Connecting to voice...
2022-06-09 15:33:22,525 INFO: Starting voice handshake... (connection attempt 1)
2022-06-09 15:33:23,251 INFO: Voice handshake complete. Endpoint found japan8919.discord.media
2022-06-09 15:33:24,259 INFO: selected the voice protocol for use (xsalsa20_poly1305_lite)
2022-06-09 15:33:24,423 INFO: received secret key for voice connection
2022-06-09 15:33:26,243 INFO: Preparing to terminate ffmpeg process 1923.
2022-06-09 15:33:26,243 INFO: ffmpeg process 1923 successfully terminated with return code of 0.
2022-06-09 15:33:27,254 INFO: The voice handshake is being terminated for Channel ID 728631391809437746 (Guild ID 428109526550708234)
2022-06-09 15:33:27,255 INFO: Disconnecting from voice normally, close code 1000.
2022-06-09 15:34:09,927 INFO: KyrieR in 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 15:34:10,002 INFO: Connecting to voice...
2022-06-09 15:34:10,021 INFO: Starting voice handshake... (connection attempt 1)
2022-06-09 15:34:10,226 INFO: Voice handshake complete. Endpoint found japan8919.discord.media
2022-06-09 15:34:11,234 INFO: selected the voice protocol for use (xsalsa20_poly1305_lite)
2022-06-09 15:34:11,399 INFO: received secret key for voice connection
2022-06-09 15:34:14,022 INFO: Preparing to terminate ffmpeg process 1934.
2022-06-09 15:34:14,022 INFO: ffmpeg process 1934 successfully terminated with return code of 0.
2022-06-09 15:34:16,106 INFO: Preparing to terminate ffmpeg process 1944.
2022-06-09 15:34:16,107 INFO: ffmpeg process 1944 successfully terminated with return code of 0.
2022-06-09 15:34:17,150 INFO: The voice handshake is being terminated for Channel ID 728631391809437746 (Guild ID 428109526550708234)
2022-06-09 15:34:17,151 INFO: Disconnecting from voice normally, close code 1000.
2022-06-09 15:36:59,772 INFO: KyrieR out 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 15:36:59,773 INFO: Connecting to voice...
2022-06-09 15:36:59,773 INFO: Starting voice handshake... (connection attempt 1)
2022-06-09 15:37:00,510 INFO: Voice handshake complete. Endpoint found japan8919.discord.media
2022-06-09 15:37:01,519 INFO: selected the voice protocol for use (xsalsa20_poly1305_lite)
2022-06-09 15:37:01,708 INFO: received secret key for voice connection
2022-06-09 15:37:03,522 INFO: Preparing to terminate ffmpeg process 1985.
2022-06-09 15:37:03,523 INFO: ffmpeg process 1985 successfully terminated with return code of 0.
2022-06-09 15:37:04,529 INFO: The voice handshake is being terminated for Channel ID 728631391809437746 (Guild ID 428109526550708234)
2022-06-09 15:37:04,532 INFO: Disconnecting from voice normally, close code 1000.
2022-06-09 15:37:46,838 INFO: KyrieR in 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 15:37:46,869 INFO: Connecting to voice...
2022-06-09 15:37:46,870 INFO: Starting voice handshake... (connection attempt 1)
2022-06-09 15:37:47,144 INFO: Voice handshake complete. Endpoint found japan8919.discord.media
2022-06-09 15:37:48,162 INFO: selected the voice protocol for use (xsalsa20_poly1305_lite)
2022-06-09 15:37:48,332 INFO: received secret key for voice connection
2022-06-09 15:37:50,439 INFO: Preparing to terminate ffmpeg process 1996.
2022-06-09 15:37:50,439 INFO: ffmpeg process 1996 successfully terminated with return code of 0.
2022-06-09 15:37:53,466 INFO: Preparing to terminate ffmpeg process 2006.
2022-06-09 15:37:53,466 INFO: ffmpeg process 2006 successfully terminated with return code of 0.
2022-06-09 15:37:54,497 INFO: The voice handshake is being terminated for Channel ID 728631391809437746 (Guild ID 428109526550708234)
2022-06-09 15:37:54,499 INFO: Disconnecting from voice normally, close code 1000.
2022-06-09 15:41:46,734 INFO: logging in using static token
2022-06-09 15:41:47,022 INFO: Shard ID None has sent the IDENTIFY payload.
2022-06-09 15:41:47,167 INFO: Shard ID None has connected to Gateway: ["gateway-prd-main-f06h",{"micros":99628,"calls":["discord-sessions-blue-prd-2-33",{"micros":97451,"calls":["start_session",{"micros":58557,"calls":["discord-api-7bb9cf8b55-ffppf",{"micros":51208,"calls":["get_user",{"micros":9351},"add_authorized_ip",{"micros":4493},"get_guilds",{"micros":11376},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":42,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: dd084805689f4edd6903f1842181d8c3).
2022-06-09 15:41:49,242 INFO: 目前登入身份：神奇海螺#3847
2022-06-09 16:05:13,979 INFO: 楓夜 in 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 16:05:14,023 INFO: Connecting to voice...
2022-06-09 16:05:14,024 INFO: Starting voice handshake... (connection attempt 1)
2022-06-09 16:05:14,750 INFO: Voice handshake complete. Endpoint found japan8919.discord.media
2022-06-09 16:05:15,772 INFO: selected the voice protocol for use (xsalsa20_poly1305_lite)
2022-06-09 16:05:15,942 INFO: received secret key for voice connection
2022-06-09 16:05:18,379 INFO: Preparing to terminate ffmpeg process 172.
2022-06-09 16:05:18,379 INFO: ffmpeg process 172 successfully terminated with return code of 0.
2022-06-09 16:05:20,545 INFO: Preparing to terminate ffmpeg process 183.
2022-06-09 16:05:20,547 INFO: ffmpeg process 183 successfully terminated with return code of 0.
2022-06-09 16:05:21,609 INFO: The voice handshake is being terminated for Channel ID 728631391809437746 (Guild ID 428109526550708234)
2022-06-09 16:05:21,610 INFO: Disconnecting from voice normally, close code 1000.
2022-06-09 16:12:46,733 INFO: 楓夜 out 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 16:12:46,735 INFO: Connecting to voice...
2022-06-09 16:12:46,736 INFO: Starting voice handshake... (connection attempt 1)
2022-06-09 16:12:47,458 INFO: Voice handshake complete. Endpoint found japan8919.discord.media
2022-06-09 16:12:48,465 INFO: selected the voice protocol for use (xsalsa20_poly1305_lite)
2022-06-09 16:12:48,631 INFO: received secret key for voice connection
2022-06-09 16:12:50,980 INFO: Preparing to terminate ffmpeg process 225.
2022-06-09 16:12:50,981 INFO: ffmpeg process 225 successfully terminated with return code of 0.
2022-06-09 16:12:52,053 INFO: The voice handshake is being terminated for Channel ID 728631391809437746 (Guild ID 428109526550708234)
2022-06-09 16:12:52,054 INFO: Disconnecting from voice normally, close code 1000.
2022-06-09 16:54:14,355 INFO: BunnyplayGG out 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 16:54:14,355 INFO: Connecting to voice...
2022-06-09 16:54:14,355 INFO: Starting voice handshake... (connection attempt 1)
2022-06-09 16:54:15,102 INFO: Voice handshake complete. Endpoint found japan8919.discord.media
2022-06-09 16:54:15,939 INFO: Chi out 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 16:54:16,123 INFO: selected the voice protocol for use (xsalsa20_poly1305_lite)
2022-06-09 16:54:16,292 INFO: received secret key for voice connection
2022-06-09 16:54:18,665 INFO: Preparing to terminate ffmpeg process 357.
2022-06-09 16:54:18,666 INFO: ffmpeg process 357 successfully terminated with return code of 0.
2022-06-09 16:54:21,342 INFO: Preparing to terminate ffmpeg process 367.
2022-06-09 16:54:21,343 INFO: ffmpeg process 367 successfully terminated with return code of 0.
2022-06-09 16:54:22,391 INFO: The voice handshake is being terminated for Channel ID 728631391809437746 (Guild ID 428109526550708234)
2022-06-09 16:54:22,392 INFO: Disconnecting from voice normally, close code 1000.
2022-06-09 16:54:24,580 INFO: KyrieR out 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 16:54:24,589 INFO: Connecting to voice...
2022-06-09 16:54:24,589 INFO: Starting voice handshake... (connection attempt 1)
2022-06-09 16:54:24,874 INFO: Voice handshake complete. Endpoint found japan8919.discord.media
2022-06-09 16:54:25,873 INFO: selected the voice protocol for use (xsalsa20_poly1305_lite)
2022-06-09 16:54:26,043 INFO: received secret key for voice connection
2022-06-09 16:54:27,856 INFO: Preparing to terminate ffmpeg process 378.
2022-06-09 16:54:27,857 INFO: ffmpeg process 378 successfully terminated with return code of 0.
2022-06-09 16:54:28,866 INFO: The voice handshake is being terminated for Channel ID 728631391809437746 (Guild ID 428109526550708234)
2022-06-09 16:54:28,867 INFO: Disconnecting from voice normally, close code 1000.
2022-06-09 16:57:03,393 INFO: 不偷家的飄飄大仙 out 9又4分之8.7月台[123是什麼敷衍的名字]
2022-06-09 16:57:03,393 INFO: Connecting to voice...
2022-06-09 16:57:03,394 INFO: Starting voice handshake... (connection attempt 1)
2022-06-09 16:57:04,073 INFO: Voice handshake complete. Endpoint found japan8919.discord.media
2022-06-09 16:57:05,088 INFO: selected the voice protocol for use (xsalsa20_poly1305_lite)
2022-06-09 16:57:05,258 INFO: received secret key for voice connection
2022-06-09 16:57:08,163 INFO: Preparing to terminate ffmpeg process 389.
2022-06-09 16:57:08,163 INFO: ffmpeg process 389 successfully terminated with return code of 0.
2022-06-09 16:57:09,209 INFO: The voice handshake is being terminated for Channel ID 728631391809437746 (Guild ID 428109526550708234)
2022-06-09 16:57:09,210 INFO: Disconnecting from voice normally, close code 1000.
2022-06-09 18:07:47,654 INFO: Got a request to RESUME the websocket.
2022-06-09 18:07:47,828 INFO: Shard ID None has sent the RESUME payload.
2022-06-09 18:07:47,868 INFO: Shard ID None has successfully RESUMED session dd084805689f4edd6903f1842181d8c3 under trace ["gateway-prd-main-th7b",{"micros":931,"calls":["discord-sessions-blue-prd-2-33",{"micros":24}]}].
